In [2]:
#Load data science libraries
import pandas
import numpy

#Load data vizualisation library
import matplotlib.pyplot as plt
import seaborn

#Change pandas display options
pandas.options.display.max_columns = None

/home/keberger/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)
/home/keberger/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)
/home/keberger/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)


# Load Dataset 

In [3]:
df = pandas.read_excel("../data/clean_train_dataset.xlsx")
print(df.shape)
df.head()

(891, 11)


Survived  Pclass  Age  SibSp  Parch  Fare  C  Q  S  female  male
0         0       3   22      1      0     7  0  0  1       0     1
1         1       1   38      1      0    71  1  0  0       1     0
2         1       3   26      0      0     7  0  0  1       1     0
3         1       1   35      1      0    53  0  0  1       1     0
4         0       3   35      0      0     8  0  0  1       0     1

# Sanity Check 

In [4]:
df.isnull().sum()/len(df)

Survived    0.0
Pclass      0.0
Age         0.0
SibSp       0.0
Parch       0.0
Fare        0.0
C           0.0
Q           0.0
S           0.0
female      0.0
male        0.0
dtype: float64

# Train Test split

In [5]:
from sklearn.model_selection import train_test_split
X = df.drop("Survived",axis = 1)
Y = df.Survived
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2)
print('X_train =',X_train.shape)
print('X_test =',X_test.shape)
print('Y_train =',Y_train.shape)
print('Y_test =',Y_test.shape)

X_train = (712, 10)
X_test = (179, 10)
Y_train = (712,)
Y_test = (179,)


# Define metrics based on confusion matrix

In [6]:
from sklearn.metrics import confusion_matrix,classification_report
def get_confusion_matrix(y_test,y_pred):
    cm = confusion_matrix(y_test,y_pred)
    print(cm)
    print( classification_report(y_test,y_pred))

# Models

## Random Forest Classifier

In [7]:
from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier(n_estimators=1000, # Number of trees
                                  max_features=2,    # Num features considered
                                  bootstrap = False)
forest.fit(X_train,Y_train)
Y_pred = forest.predict(X_test)
get_confusion_matrix(Y_pred,Y_test)

[[91 20]
 [21 47]]
             precision    recall  f1-score   support

          0       0.81      0.82      0.82       111
          1       0.70      0.69      0.70        68

avg / total       0.77      0.77      0.77       179



## Adaboost Classifier 

In [10]:
from sklearn.ensemble import AdaBoostClassifier
adaboost = AdaBoostClassifier(n_estimators=200)
adaboost.fit(X_train,Y_train)
Y_pred = adaboost.predict(X_test)
get_confusion_matrix(Y_pred,Y_test)

[[93 19]
 [19 48]]
             precision    recall  f1-score   support

          0       0.83      0.83      0.83       112
          1       0.72      0.72      0.72        67

avg / total       0.79      0.79      0.79       179



## Bagging Classifier

In [11]:
from sklearn.ensemble import BaggingClassifier
bagging = BaggingClassifier(n_estimators=200)
bagging.fit(X_train,Y_train)
Y_pred = bagging.predict(X_test)
get_confusion_matrix(Y_pred,Y_test)

[[97 17]
 [15 50]]
             precision    recall  f1-score   support

          0       0.87      0.85      0.86       114
          1       0.75      0.77      0.76        65

avg / total       0.82      0.82      0.82       179



##  ExtraTree Classifier

In [12]:
from sklearn.ensemble import ExtraTreesClassifier
ExtraTrees = ExtraTreesClassifier(n_estimators=200)
ExtraTrees.fit(X_train,Y_train)
Y_pred = ExtraTrees.predict(X_test)
get_confusion_matrix(Y_pred,Y_test)

[[92 17]
 [20 50]]
             precision    recall  f1-score   support

          0       0.82      0.84      0.83       109
          1       0.75      0.71      0.73        70

avg / total       0.79      0.79      0.79       179



## Gradient Boosting Classifier

In [13]:
from sklearn.ensemble import GradientBoostingClassifier
GradientBoosting = GradientBoostingClassifier(n_estimators=200)
GradientBoosting.fit(X_train,Y_train)
Y_pred = GradientBoosting.predict(X_test)
get_confusion_matrix(Y_pred,Y_test)

[[101  20]
 [ 11  47]]
             precision    recall  f1-score   support

          0       0.90      0.83      0.87       121
          1       0.70      0.81      0.75        58

avg / total       0.84      0.83      0.83       179

