In [1]:
#Load data science libraries
import pandas
import numpy

#Load data vizualisation library
import matplotlib.pyplot as plt
import seaborn

#Change pandas display options
pandas.options.display.max_columns = None

/home/keberger/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)
/home/keberger/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)
/home/keberger/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)
/home/keberger/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)


# Load Dataset 

In [2]:
df = pandas.read_excel("../data/clean_train_dataset.xlsx")
print(df.shape)
df.head()

(891, 11)


Survived  Pclass  Age  SibSp  Parch  Fare  C  Q  S  female  male
0         0       3   22      1      0     7  0  0  1       0     1
1         1       1   38      1      0    71  1  0  0       1     0
2         1       3   26      0      0     7  0  0  1       1     0
3         1       1   35      1      0    53  0  0  1       1     0
4         0       3   35      0      0     8  0  0  1       0     1

# Sanity Check 

In [3]:
df.isnull().sum()/len(df)

Survived    0.0
Pclass      0.0
Age         0.0
SibSp       0.0
Parch       0.0
Fare        0.0
C           0.0
Q           0.0
S           0.0
female      0.0
male        0.0
dtype: float64

# Train Test split

In [4]:
from sklearn.model_selection import train_test_split
X = df.drop("Survived",axis = 1)
Y = df.Survived
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2)
print('X_train =',X_train.shape)
print('X_test =',X_test.shape)
print('Y_train =',Y_train.shape)
print('Y_test =',Y_test.shape)

X_train = (712, 10)
X_test = (179, 10)
Y_train = (712,)
Y_test = (179,)


/home/keberger/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)


# Define metrics based on confusion matrix

In [5]:
from sklearn.metrics import confusion_matrix,classification_report
def get_confusion_matrix(y_test,y_pred):
    cm = confusion_matrix(y_test,y_pred)
    print(cm)
    print( classification_report(y_test,y_pred))

# Models

## Passive Aggressive Classifier

In [6]:
from sklearn.linear_model import PassiveAggressiveClassifier
passiveAggressive = PassiveAggressiveClassifier(max_iter = 1000)
passiveAggressive.fit(X_train,Y_train)
Y_pred = passiveAggressive.predict(X_test)
get_confusion_matrix(Y_pred,Y_test)

[[113  47]
 [  1  18]]
             precision    recall  f1-score   support

          0       0.99      0.71      0.82       160
          1       0.28      0.95      0.43        19

avg / total       0.92      0.73      0.78       179



## Ridge Classifier 

In [7]:
from sklearn.linear_model import RidgeClassifier
Ridge = RidgeClassifier(max_iter = 1000)
Ridge.fit(X_train,Y_train)
Y_pred = Ridge.predict(X_test)
get_confusion_matrix(Y_pred,Y_test)

[[99 13]
 [15 52]]
             precision    recall  f1-score   support

          0       0.87      0.88      0.88       112
          1       0.80      0.78      0.79        67

avg / total       0.84      0.84      0.84       179



## SGD Classifier

In [8]:
from sklearn.linear_model import SGDClassifier
SGD = SGDClassifier(max_iter = 1000)
SGD.fit(X_train,Y_train)
Y_pred = SGD.predict(X_test)
get_confusion_matrix(Y_pred,Y_test)

[[103  38]
 [ 11  27]]
             precision    recall  f1-score   support

          0       0.90      0.73      0.81       141
          1       0.42      0.71      0.52        38

avg / total       0.80      0.73      0.75       179

