In [1]:
#Load data science libraries
import pandas
import numpy

#Load data vizualisation library
import matplotlib.pyplot as plt
import seaborn

#Change pandas display options
pandas.options.display.max_columns = None

# Load Dataset 

In [2]:
df = pandas.read_excel("../data/clean_train_dataset.xlsx")
print(df.shape)
df.head()

(891, 11)


Survived  Pclass  Age  SibSp  Parch  Fare  C  Q  S  female  male
0         0       3   22      1      0     7  0  0  1       0     1
1         1       1   38      1      0    71  1  0  0       1     0
2         1       3   26      0      0     7  0  0  1       1     0
3         1       1   35      1      0    53  0  0  1       1     0
4         0       3   35      0      0     8  0  0  1       0     1

# Sanity Check 

In [3]:
df.isnull().sum()/len(df)

Survived    0.0
Pclass      0.0
Age         0.0
SibSp       0.0
Parch       0.0
Fare        0.0
C           0.0
Q           0.0
S           0.0
female      0.0
male        0.0
dtype: float64

# Train Test split

In [4]:
from sklearn.model_selection import train_test_split
X = df.drop("Survived",axis = 1)
Y = df.Survived
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2)
print('X_train =',X_train.shape)
print('X_test =',X_test.shape)
print('Y_train =',Y_train.shape)
print('Y_test =',Y_test.shape)

X_train = (712, 10)
X_test = (179, 10)
Y_train = (712,)
Y_test = (179,)


# Define metrics based on confusion matrix

In [5]:
from sklearn.metrics import confusion_matrix,classification_report
def get_confusion_matrix(y_test,y_pred):
    cm = confusion_matrix(y_test,y_pred)
    print(cm)
    print( classification_report(y_test,y_pred))

# Models

## BernoulliNB

In [7]:
from sklearn.naive_bayes import BernoulliNB
BernoulliNB = BernoulliNB()
BernoulliNB.fit(X_train,Y_train)
Y_pred = BernoulliNB.predict(X_test)
get_confusion_matrix(Y_pred,Y_test)

[[98 16]
 [19 46]]
             precision    recall  f1-score   support

          0       0.84      0.86      0.85       114
          1       0.74      0.71      0.72        65

avg / total       0.80      0.80      0.80       179



## Gaussian

In [9]:
from sklearn.naive_bayes import GaussianNB
gaussianNB = GaussianNB()
gaussianNB.fit(X_train,Y_train)
Y_pred = gaussianNB.predict(X_test)
get_confusion_matrix(Y_pred,Y_test)

[[89 17]
 [28 45]]
             precision    recall  f1-score   support

          0       0.76      0.84      0.80       106
          1       0.73      0.62      0.67        73

avg / total       0.75      0.75      0.74       179



## Multinomial NB

In [16]:
from sklearn.naive_bayes import MultinomialNB
MultinomialNB = MultinomialNB()
MultinomialNB.fit(X_train,Y_train)
Y_pred = MultinomialNB.predict(X_test)
get_confusion_matrix(Y_pred,Y_test)

[[94 28]
 [23 34]]
             precision    recall  f1-score   support

          0       0.80      0.77      0.79       122
          1       0.55      0.60      0.57        57

avg / total       0.72      0.72      0.72       179

